# Dynamic configuration

[[tls.certificates]]
  certFile = "/certs/traefik.crt"
  keyFile = "/certs/traefik.key"

[[tls.certificates]]
  certFile = "/certs/gitlab.crt"
  keyFile = "/certs/gitlab.key"

[[tls.certificates]]
  certFile = "/certs/rocketchat.crt"
  keyFile = "/certs/rocketchat.key"

[[tls.certificates]]
  certFile = "/certs/wikijs.crt"
  keyFile = "/certs/wikijs.key"

[[tls.certificates]]
  certFile = "/certs/nextcloud.crt"
  keyFile = "/certs/nextcloud.key"